name: Run npc_gzip tests

on: [push, pull_request]

jobs:

  run-tests:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Show Poetry version
        run: poetry --version

      - name: Install project and dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest --junit-xml=junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        if: ${{ !cancelled() }}  # Upload results even if tests fail.
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml
